"""initial

Revision ID: bc861d13f737
Revises: 
Create Date: 2026-04-24 14:58:20.092023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc861d13f737'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persoon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voornaam', sa.String(length=100), nullable=False),
    sa.Column('achternaam', sa.String(length=100), nullable=False),
    sa.Column('geboorte_datum', sa.Date(), nullable=True),
    sa.Column('geboorte_plaats', sa.String(length=200), nullable=True),
    sa.Column('sterf_datum', sa.Date(), nullable=True),
    sa.Column('sterf_plaats', sa.String(length=200), nullable=True),
    sa.Column('begraven_locatie', sa.String(length=300), nullable=True),
    sa.Column('geslacht', sa.Enum('M', 'V', 'X', name='geslacht'), nullable=True),
    sa.Column('notities', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persoon_id'), 'persoon', ['id'], unique=False)
    op.create_table('ouderschap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind_id', sa.Integer(), nullable=False),
    sa.Column('ouder_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('biologisch', 'adoptief', 'pleeg', name='ouderschaptype'), nullable=False),
    sa.ForeignKeyConstraint(['kind_id'], ['persoon.id'], ),
    sa.ForeignKeyConstraint(['ouder_id'], ['persoon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ouderschap_id'), 'ouderschap', ['id'], unique=False)
    op.create_table('relatie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persoon_a_id', sa.Integer(), nullable=False),
    sa.Column('persoon_b_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('getrouwd', 'samenwonend', 'gescheiden', name='relatietype'), nullable=False),
    sa.Column('datum_start', sa.Date(), nullable=True),
    sa.Column('plaats_start', sa.String(length=200), nullable=True),
    sa.Column('datum_einde', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['persoon_a_id'], ['persoon.id'], ),
    sa.ForeignKeyConstraint(['persoon_b_id'], ['persoon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relatie_id'), 'relatie', ['id'], unique=False)
    op.create_table('bijlage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persoon_id', sa.Integer(), nullable=True),
    sa.Column('relatie_id', sa.Integer(), nullable=True),
    sa.Column('bestandsnaam', sa.String(length=255), nullable=False),
    sa.Column('bestandspad', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('foto', 'document', 'overig', name='bijlagetype'), nullable=False),
    sa.Column('omschrijving', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['persoon_id'], ['persoon.id'], ),
    sa.ForeignKeyConstraint(['relatie_id'], ['relatie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bijlage_id'), 'bijlage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bijlage_id'), table_name='bijlage')
    op.drop_table('bijlage')
    op.drop_index(op.f('ix_relatie_id'), table_name='relatie')
    op.drop_table('relatie')
    op.drop_index(op.f('ix_ouderschap_id'), table_name='ouderschap')
    op.drop_table('ouderschap')
    op.drop_index(op.f('ix_persoon_id'), table_name='persoon')
    op.drop_table('persoon')
    # ### end Alembic commands ###
